"""Optional Supabase account persistence with application-level encryption.

The browser/session authenticates as a normal Supabase user. Row Level Security
enforces ownership; sensitive API keys, cases, references, answers and judgments
are encrypted before leaving the application process.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from cryptography.fernet import Fernet, InvalidToken
from supabase import Client, create_client

from benchmark.schema import RunArtifact


@dataclass(frozen=True)
class AccountSession:
    user_id: str
    email: str
    access_token: str
    refresh_token: str


def configured() -> bool:
    return bool(
        os.environ.get("SUPABASE_URL")
        and os.environ.get("SUPABASE_ANON_KEY")
        and os.environ.get("APP_ENCRYPTION_KEY")
    )


def _fernet() -> Fernet:
    raw = (os.environ.get("APP_ENCRYPTION_KEY") or "").encode("ascii")
    if not raw:
        raise RuntimeError("APP_ENCRYPTION_KEY is not configured")
    try:
        return Fernet(raw)
    except (ValueError, TypeError) as exc:
        raise RuntimeError(
            "APP_ENCRYPTION_KEY must be a Fernet key generated by Fernet.generate_key()"
        ) from exc


def _client() -> Client:
    url = os.environ.get("SUPABASE_URL") or ""
    anon = os.environ.get("SUPABASE_ANON_KEY") or ""
    if not url or not anon:
        raise RuntimeError("Supabase is not configured")
    return create_client(url, anon)


def _authenticated(session: AccountSession) -> Client:
    client = _client()
    client.auth.set_session(session.access_token, session.refresh_token)
    return client


def sign_in(email: str, password: str) -> AccountSession:
    response = _client().auth.sign_in_with_password(
        {"email": email.strip(), "password": password}
    )
    if not response.user or not response.session:
        raise RuntimeError("Supabase sign-in did not return a session")
    return AccountSession(
        user_id=str(response.user.id),
        email=str(response.user.email or email),
        access_token=response.session.access_token,
        refresh_token=response.session.refresh_token,
    )


def sign_up(email: str, password: str) -> Optional[AccountSession]:
    response = _client().auth.sign_up(
        {"email": email.strip(), "password": password}
    )
    if not response.user:
        raise RuntimeError("Supabase sign-up failed")
    if not response.session:
        return None  # email confirmation required
    return AccountSession(
        user_id=str(response.user.id),
        email=str(response.user.email or email),
        access_token=response.session.access_token,
        refresh_token=response.session.refresh_token,
    )


def encrypt_text(value: str) -> str:
    return _fernet().encrypt(value.encode("utf-8")).decode("ascii")


def decrypt_text(value: str) -> str:
    try:
        return _fernet().decrypt(value.encode("ascii")).decode("utf-8")
    except InvalidToken as exc:
        raise RuntimeError(
            "Encrypted value cannot be opened with the configured key"
        ) from exc


def save_openrouter_key(session: AccountSession, api_key: str) -> None:
    client = _authenticated(session)
    client.table("user_secrets").upsert(
        {
            "user_id": session.user_id,
            "secret_name": "openrouter_api_key",
            "ciphertext": encrypt_text(api_key.strip()),
        },
        on_conflict="user_id,secret_name",
    ).execute()


def load_openrouter_key(session: AccountSession) -> str:
    response = (
        _authenticated(session)
        .table("user_secrets")
        .select("ciphertext")
        .eq("user_id", session.user_id)
        .eq("secret_name", "openrouter_api_key")
        .maybe_single()
        .execute()
    )
    row = response.data
    return decrypt_text(str(row["ciphertext"])) if row else ""


def save_artifact(session: AccountSession, artifact: RunArtifact) -> None:
    payload = artifact.model_dump_json()
    _authenticated(session).table("benchmark_artifacts").upsert(
        {
            "user_id": session.user_id,
            "run_id": artifact.run_id,
            "case_id": artifact.case_id,
            "cohort_id": artifact.cohort_id,
            "run_status": artifact.run_status,
            "ciphertext": encrypt_text(payload),
        },
        on_conflict="user_id,run_id",
    ).execute()


def list_artifacts(
    session: AccountSession, *, case_id: Optional[str] = None, limit: int = 100
) -> List[Dict[str, Any]]:
    query = (
        _authenticated(session)
        .table("benchmark_artifacts")
        .select("run_id,case_id,cohort_id,run_status,created_at,ciphertext")
        .eq("user_id", session.user_id)
        .order("created_at", desc=True)
        .limit(max(1, min(int(limit), 500)))
    )
    if case_id:
        query = query.eq("case_id", case_id)
    response = query.execute()
    rows: List[Dict[str, Any]] = []
    for raw in response.data or []:
        row = dict(raw)
        artifact = RunArtifact.model_validate_json(
            decrypt_text(str(row.pop("ciphertext")))
        )
        row["artifact"] = artifact
        rows.append(row)
    return rows


def delete_artifact(session: AccountSession, run_id: str) -> None:
    (
        _authenticated(session)
        .table("benchmark_artifacts")
        .delete()
        .eq("user_id", session.user_id)
        .eq("run_id", run_id)
        .execute()
    )
